services:
  - type: web
    name: subzero-md
    runtime: docker
    dockerfilePath: /Dockerfile
    envVars:
      - key: SESSION_ID
        value: ""
      - key: OWNER_NUMBER
        value: "2349157872959"
      - key: BOT_NAME
        value: "BISHOP-MD"
      - key: COMMAND_MODE
        value: "private"
      - key: TIMEZONE
        value: "Africa/Harare"
      - key: MONGO_URL
        value: ""
      - key: POSTGRES_URL
        value: ""
      - key: MYSQL_URL
        value: ""
      - key: DB_URL
        value: ""
    startCommand: npm start:optimized
